### ISSUE TITLE
Getting parse error when I call a cloud function

### ISSUE THREAD

**Issue by mkulumadzi** [GiveNow/givenow-ios#81]
Seeing something like these each time I call a cloud function:

2016-01-28 13:34:55.207 GiveNow[6744:2139611] [Error]: TypeError: Cannot call a class as a function
    at r.default (Parse.js:16:7159)
    at Object.e [as Query](Parse.js:14:30051)
    at Object.module.exports.getLocalization (services/LocalizationService.js:3:23)
    at e.<anonymous> (services/PushService.js:54:27)
    at e.s (Parse.js:14:27156)
    at e.n.value (Parse.js:14:26575)
    at e.<anonymous> (Parse.js:14:27228)
    at e.s (Parse.js:14:27156)
    at Parse.js:14:27542
    at i (Parse.js:14:27497) (Code: 141, Version: 1.11.0)
Error Domain=Parse Code=141 "TypeError: Cannot call a class as a function
    at r.default (Parse.js:16:7159)
    at Object.e [as Query](Parse.js:14:30051)
    at Object.module.exports.getLocalization (services/LocalizationService.js:3:23)
    at e.<anonymous> (services/PushService.js:54:27)
    at e.s (Parse.js:14:27156)
    at e.n.value (Parse.js:14:26575)
    at e.<anonymous> (Parse.js:14:27228)
    at e.s (Parse.js:14:27156)
    at Parse.js:14:27542
    at i (Parse.js:14:27497)" UserInfo={code=141, temporary=0, error=TypeError: Cannot call a class as a function
    at r.default (Parse.js:16:7159)
    at Object.e [as Query](Parse.js:14:30051)
    at Object.module.exports.getLocalization (services/LocalizationService.js:3:23)
    at e.<anonymous> (services/PushService.js:54:27)
    at e.s (Parse.js:14:27156)
    at e.n.value (Parse.js:14:26575)
    at e.<anonymous> (Parse.js:14:27228)
    at e.s (Parse.js:14:27156)
    at Parse.js:14:27542
    at i (Parse.js:14:27497), NSLocalizedDescription=TypeError: Cannot call a class as a function
    at r.default (Parse.js:16:7159)
    at Object.e [as Query](Parse.js:14:30051)
    at Object.module.exports.getLocalization (services/LocalizationService.js:3:23)
    at e.<anonymous> (services/PushService.js:54:27)
    at e.s (Parse.js:14:27156)
    at e.n.value (Parse.js:14:26575)
    at e.<anonymous> (Parse.js:14:27228)
    at e.s (Parse.js:14:27156)
    at Parse.js:14:27542
    at i (Parse.js:14:27497)}

**Comment by aphexcx** [comment]
No worries, I'm in the midst of updating SMS localization cloud code. This will go away later today

**Comment by aphexcx** [comment]
Cloud code is operational!
